service: fh4-tune

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
